This project contains some CoAP examples. The jar file included in the lib 
folder is a light version of Californium CoAP framework, generated by the Cal-lite
project (https://github.com/nikosft/Cal-lite).

Examples
--------

Hello World
-----------
It creates a resource that can be accessed using the GET method. The resource
returns a simple message.

Hello World POST
----------------
It creates a resource that can be accessed using the POST method. The resource
echoes back the posted message.
